services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: host
    environment:
      - TZ=America/Chicago
      - FTLCONF_webserver_api_password=YOUR_PASSWORD_HERE
      - FTLCONF_webserver_port=8081
      - FTLCONF_dns_listeningMode=all
      - PIHOLE_DNS_=1.1.1.1;1.0.0.1
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
